### ISSUE TITLE
Pet投稿の地域２について

### ISSUE THREAD

**Issue by Kazuya-Sakashita** [igeeeeee/zerowan#11]
figmaのレイアウトでは地域２がて入力で存在しているが、
DBには都道府県しかない。どうするか？

**Comment by Kazuya-Sakashita** [comment]
ゼロワンの機能一覧では都道府県のプルダウンのみ。

**Comment by igeeeeee** [comment]
地域２で市区町村を入れると都道府県と合体させるのが大変そうなので、地域２は消して地域１を受け取り地域とかにして都道府県を選択の形にしようと思います。

**Comment by Kazuya-Sakashita** [comment]
仕様の通りの都道府県のプルダウンのみで運用で決定。
